// AUTOGENERATED by scripts/sample-legend.mjs - do not edit by hand.
// Run `node scripts/sample-legend.mjs` to regenerate from the sample PDF.

import type { RoadCategory } from "@/lib/road-detect";

export interface LegendSwatch {
  category: RoadCategory;
  rgb: [number, number, number];
  tolerance: number;
}

export const LEGEND_SWATCHES: LegendSwatch[] = [
  {
    "category": "road_row",
    "rgb": [
      210,
      166,
      121
    ],
    "tolerance": 22
  },
  {
    "category": "road_plot",
    "rgb": [
      255,
      255,
      112
    ],
    "tolerance": 22
  },
  {
    "category": "taxi_layby",
    "rgb": [
      161,
      92,
      184
    ],
    "tolerance": 22
  },
  {
    "category": "shuttle_layby",
    "rgb": [
      110,
      221,
      0
    ],
    "tolerance": 22
  },
  {
    "category": "emergency_access",
    "rgb": [
      254,
      222,
      221
    ],
    "tolerance": 22
  },
  {
    "category": "apartment_access",
    "rgb": [
      159,
      191,
      223
    ],
    "tolerance": 22
  },
  {
    "category": "plot_access",
    "rgb": [
      255,
      214,
      173
    ],
    "tolerance": 22
  },
  {
    "category": "bridge",
    "rgb": [
      71,
      163,
      255
    ],
    "tolerance": 22
  },
  {
    "category": "bridge_ramp",
    "rgb": [
      119,
      192,
      228
    ],
    "tolerance": 22
  },
  {
    "category": "tunnel",
    "rgb": [
      232,
      163,
      255
    ],
    "tolerance": 22
  },
  {
    "category": "tunnel_ramp",
    "rgb": [
      255,
      179,
      198
    ],
    "tolerance": 22
  },
  {
    "category": "raised_crossing",
    "rgb": [
      64,
      64,
      64
    ],
    "tolerance": 22
  },
  {
    "category": "building",
    "rgb": [
      245,
      235,
      210
    ],
    "tolerance": 24
  },
  {
    "category": "context",
    "rgb": [
      200,
      200,
      200
    ],
    "tolerance": 14
  }
];
