// AUTOGENERATED by scripts/sample-legend.mjs - do not edit by hand.
// Run `node scripts/sample-legend.mjs` to regenerate from the sample PDF.

import type { RoadCategory } from "@/lib/road-detect";

export interface LegendSwatch {
  category: RoadCategory;
  rgb: [number, number, number];
  tolerance: number;
  aliases?: [number, number, number][];
}

export const LEGEND_SWATCHES: LegendSwatch[] = [
  {
    "category": "road_row",
    "rgb": [
      210,
      166,
      121
    ],
    "tolerance": 35
  },
  {
    "category": "road_plot",
    "rgb": [
      255,
      255,
      112
    ],
    "tolerance": 35
  },
  {
    "category": "taxi_layby",
    "rgb": [
      161,
      92,
      184
    ],
    "tolerance": 35
  },
  {
    "category": "shuttle_layby",
    "rgb": [
      110,
      221,
      0
    ],
    "tolerance": 35
  },
  {
    "category": "emergency_access",
    "rgb": [
      254,
      222,
      221
    ],
    "tolerance": 35
  },
  {
    "category": "apartment_access",
    "rgb": [
      159,
      191,
      223
    ],
    "tolerance": 35
  },
  {
    "category": "plot_access",
    "rgb": [
      255,
      214,
      173
    ],
    "tolerance": 35
  },
  {
    "category": "bridge",
    "rgb": [
      71,
      163,
      255
    ],
    "tolerance": 35
  },
  {
    "category": "bridge_ramp",
    "rgb": [
      119,
      192,
      228
    ],
    "tolerance": 35
  },
  {
    "category": "tunnel",
    "rgb": [
      232,
      163,
      255
    ],
    "tolerance": 35
  },
  {
    "category": "tunnel_ramp",
    "rgb": [
      255,
      179,
      198
    ],
    "tolerance": 35
  },
  {
    "category": "raised_crossing",
    "rgb": [
      64,
      64,
      64
    ],
    "tolerance": 35
  },
  {
    "category": "greenery",
    "rgb": [
      230,
      245,
      234
    ],
    "tolerance": 22,
    "aliases": [
      [
        249,
        248,
        244
      ],
      [
        210,
        242,
        214
      ],
      [
        217,
        232,
        216
      ],
      [
        203,
        236,
        211
      ],
      [
        207,
        241,
        212
      ],
      [
        214,
        233,
        202
      ],
      [
        202,
        231,
        201
      ]
    ]
  },
  {
    "category": "water",
    "rgb": [
      212,
      237,
      237
    ],
    "tolerance": 22,
    "aliases": [
      [
        235,
        244,
        248
      ],
      [
        206,
        238,
        238
      ],
      [
        119,
        192,
        228
      ]
    ]
  },
  {
    "category": "plot_fill",
    "rgb": [
      252,
      250,
      230
    ],
    "tolerance": 22,
    "aliases": [
      [
        233,
        233,
        217
      ]
    ]
  },
  {
    "category": "building",
    "rgb": [
      253,
      245,
      217
    ],
    "tolerance": 22,
    "aliases": [
      [
        152,
        152,
        0
      ],
      [
        255,
        255,
        112
      ],
      [
        234,
        246,
        214
      ],
      [
        210,
        166,
        121
      ],
      [
        254,
        245,
        198
      ],
      [
        248,
        230,
        197
      ],
      [
        231,
        220,
        199
      ],
      [
        246,
        236,
        216
      ],
      [
        209,
        254,
        198
      ],
      [
        231,
        229,
        203
      ],
      [
        249,
        223,
        124
      ]
    ]
  },
  {
    "category": "context",
    "rgb": [
      220,
      220,
      220
    ],
    "tolerance": 14,
    "aliases": [
      [
        231,
        231,
        230
      ],
      [
        253,
        230,
        247
      ],
      [
        131,
        131,
        130
      ],
      [
        91,
        91,
        91
      ],
      [
        165,
        155,
        151
      ],
      [
        250,
        231,
        232
      ],
      [
        251,
        216,
        246
      ],
      [
        231,
        237,
        246
      ],
      [
        254,
        206,
        243
      ],
      [
        129,
        123,
        121
      ],
      [
        125,
        122,
        120
      ],
      [
        172,
        172,
        172
      ],
      [
        248,
        216,
        216
      ],
      [
        233,
        219,
        214
      ],
      [
        215,
        215,
        200
      ],
      [
        238,
        165,
        146
      ],
      [
        254,
        206,
        219
      ],
      [
        199,
        199,
        198
      ],
      [
        205,
        203,
        186
      ],
      [
        255,
        179,
        198
      ],
      [
        162,
        162,
        124
      ],
      [
        159,
        191,
        223
      ]
    ]
  }
];
