"""Generates design/CONTENT_MANIFEST.md from the actual repository state (so status is never hand-claimed)."""
import json, pathlib, re, datetime
root = pathlib.Path(__file__).resolve().parent.parent
C = root / 'src/data/content'
sp = json.load(open(C / 'species.json'))
mv = json.load(open(C / 'moves.json'))
it = json.load(open(C / 'items.json'))
builders = {p.stem for p in (root / 'src/creatures/species').glob('c*.ts')}
zones_dir = root / 'src/data/zones'
zones = {p.stem for p in zones_dir.glob('*.json')} if zones_dir.exists() else set()
def load(name):
    p = C / name
    return json.load(open(p)) if p.exists() else []
trainers = load('trainers.json'); quests = load('quests.json'); dialogue = load('dialogue.json'); enc = load('encounters.json')
ZONES = ['town_1','route_1','forest','route_2','town_2','cave','route_3','lake','town_3','route_4','volcano','route_5','snowpeak','league','stillhouse']
out = [f"# CONTENT MANIFEST\n\nGenerated by `scripts/manifest.py` from repository state ({datetime.date.today()}). Status is derived from files, not claimed. Owner column = workstream owner (BUILD_PLAN.md).\n"]
out.append('## Creatures (30)\n\n| id | name | family | stage | types | data | 3D builder | owner |\n|---|---|---|---|---|---|---|---|')
for s in sp:
    out.append(f"| {s['id']} | {s['name']} | {s['family']} | {s['stage']} | {'/'.join(s['types'])} | species.json ✓ | {'`species/'+s['id']+'.ts` ✓' if s['id'] in builders else 'MISSING'} | builder agents |")
out.append(f"\n## Moves: {len(mv)} in moves.json (m000 fallback + {len(mv)-1}); owner systems/orchestrator\n")
types = {}
for m in mv:
    types[m['type']] = types.get(m['type'], 0) + 1
out.append('| type | moves |\n|---|---|\n' + '\n'.join(f'| {k} | {v} |' for k, v in sorted(types.items())))
out.append(f"\n## Items: {len(it)} in items.json\n\n| id | name | kind | price |\n|---|---|---|---|")
for i in it:
    out.append(f"| {i['id']} | {i['name']} | {i['kind']} | {i['price']} |")
out.append('\n## Zones (world.md v2)\n\n| zone | data file | owner |\n|---|---|---|')
for z in ZONES:
    out.append(f"| {z} | {'`zones/'+z+'.json` ✓' if z in zones else 'MISSING'} | zone agents |")
out.append(f"\n## Other content\n\n| content | count | file |\n|---|---|---|\n| trainers | {len(trainers)} | trainers.json |\n| quests | {len(quests)} | quests.json |\n| dialogue entries | {len(dialogue) if isinstance(dialogue, list) else len(dialogue.keys())} | dialogue.json |\n| encounter tables | {len(enc) if isinstance(enc, list) else len(enc.keys())} | encounters.json |\n")
(root / 'design/CONTENT_MANIFEST.md').write_text('\n'.join(out) + '\n')
print('manifest written')
