#!/usr/bin/env node
/**
 * One-off legend sampler.
 *
 * Renders public/ju_compressed_1.pdf with pdftoppm, then samples the
 * legend swatches at hand-located pixel coordinates and writes the
 * result to public/legend.json. The swatch coordinates are calibrated
 * to the layout of this specific PDF; if the sample PDF is swapped,
 * the coordinates below need recalibrating against the new render.
 *
 * Run with: node scripts/sample-legend.mjs
 */
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import sharp from "sharp";

const PDF_PATH = "public/ju_compressed_1.pdf";
const TMP_DIR = "/tmp/legend-sample";
const RENDER_DPI = 200;

const CATEGORIES = [
  { name: "road_row",          yTop: 3858, yBot: 3906 },
  { name: "road_plot",         yTop: 3922, yBot: 3970 },
  { name: "taxi_layby",        yTop: 3986, yBot: 4026 },
  { name: "shuttle_layby",     yTop: 4050, yBot: 4090 },
  { name: "emergency_access",  yTop: 4106, yBot: 4146 },
  { name: "apartment_access",  yTop: 4162, yBot: 4202 },
  { name: "plot_access",       yTop: 4226, yBot: 4266 },
  { name: "bridge",            yTop: 4282, yBot: 4322 },
  { name: "bridge_ramp",       yTop: 4346, yBot: 4386 },
  { name: "tunnel",            yTop: 4402, yBot: 4442 },
  { name: "tunnel_ramp",       yTop: 4458, yBot: 4498 },
  { name: "raised_crossing",   yTop: 4522, yBot: 4586 },
];

/** Swatch column X-range (in original render pixels). */
const SWATCH_X_START = 70;
const SWATCH_X_END = 200;

mkdirSync(TMP_DIR, { recursive: true });

if (!existsSync(`${TMP_DIR}/page-1.png`)) {
  execSync(
    `pdftoppm -r ${RENDER_DPI} -png -f 1 -l 1 ${PDF_PATH} ${TMP_DIR}/page`,
    { stdio: ["ignore", "ignore", "ignore"] }
  );
}

const img = sharp(`${TMP_DIR}/page-1.png`);
const meta = await img.metadata();
console.log(`Render: ${meta.width} x ${meta.height}`);

const raw = await img.raw().toBuffer({ resolveWithObject: true });
const { data, info } = raw;

function getPixel(x, y) {
  const i = (y * info.width + x) * info.channels;
  return [data[i], data[i + 1], data[i + 2]];
}

/** Take the mode-bin colour in a region, excluding near-white and near-black. */
function dominantColor(x0, y0, x1, y1) {
  const bins = new Map();
  for (let y = y0; y < y1; y += 2) {
    for (let x = x0; x < x1; x += 2) {
      const [r, g, b] = getPixel(x, y);
      if (r > 245 && g > 245 && b > 245) continue;
      if (r < 16 && g < 16 && b < 16) continue;
      // Quantise to 8-wide bins so dithered fills cluster.
      const key = `${r >> 3}_${g >> 3}_${b >> 3}`;
      const cur = bins.get(key) ?? { count: 0, r: 0, g: 0, b: 0 };
      cur.count += 1;
      cur.r += r;
      cur.g += g;
      cur.b += b;
      bins.set(key, cur);
    }
  }
  let best = null;
  for (const v of bins.values()) {
    if (!best || v.count > best.count) best = v;
  }
  if (!best) return [128, 128, 128];
  return [
    Math.round(best.r / best.count),
    Math.round(best.g / best.count),
    Math.round(best.b / best.count),
  ];
}

const swatches = [];
for (const { name, yTop, yBot } of CATEGORIES) {
  const rgb = dominantColor(SWATCH_X_START, yTop + 4, SWATCH_X_END, yBot - 4);
  swatches.push({ category: name, rgb, tolerance: 22 });
  console.log(`${name.padEnd(20)} y=${yTop}-${yBot}  ${rgb.join(",")}`);
}

// Add building / context defaults (not in the legend but needed by the classifier).
swatches.push({ category: "building", rgb: [245, 235, 210], tolerance: 24 });
swatches.push({ category: "context", rgb: [200, 200, 200], tolerance: 14 });

const tsBody =
  `// AUTOGENERATED by scripts/sample-legend.mjs - do not edit by hand.\n` +
  `// Run \`node scripts/sample-legend.mjs\` to regenerate from the sample PDF.\n\n` +
  `import type { RoadCategory } from "@/lib/road-detect";\n\n` +
  `export interface LegendSwatch {\n` +
  `  category: RoadCategory;\n` +
  `  rgb: [number, number, number];\n` +
  `  tolerance: number;\n` +
  `}\n\n` +
  `export const LEGEND_SWATCHES: LegendSwatch[] = ${JSON.stringify(
    swatches.map((s) => ({ ...s, rgb: s.rgb })),
    null,
    2
  )};\n`;

writeFileSync("lib/legend-swatches.ts", tsBody);
console.log("Wrote lib/legend-swatches.ts");
